apiVersion: v1
kind: Pod
metadata:
  annotations:
    com.kraken/description: "${KRAKEN_DESCRIPTION}"
    com.kraken/expectedCount: "${KRAKEN_EXPECTED_COUNT}"
  labels:
    com.kraken/taskType: "${KRAKEN_TASKTYPE}"
    com.kraken/hostId: "${KRAKEN_HOSTID}"
    com.kraken/taskId: "${KRAKEN_TASKID}"
    com.kraken/applicationId: "${KRAKEN_APPLICATION_ID}"
  name: "${KRAKEN_APPLICATION_ID}-${KRAKEN_TASKID}-${KRAKEN_HOSTID}"
spec:
  containers:
    -
      image: "octoperf/kraken-gatling-recorder:${KRAKEN_VERSION}"
      name: "${KRAKEN_APPLICATION_ID}-${KRAKEN_TASKID}-${KRAKEN_HOSTID}-${KRAKEN_GATLING_CONTAINER_NAME}"
      resources:
        limits:
          cpu: "${KRAKEN_GATLING_CPU_LIMIT}"
          memory: "${KRAKEN_GATLING_MEMORY_LIMIT}"
        requests:
          cpu: "${KRAKEN_GATLING_CPU_REQUEST}"
          memory: "${KRAKEN_GATLING_MEMORY_REQUEST}"
      env:
        - name: JAVA_OPTS
          value: "-Dspring.profiles.active=kubernetes -Xmx${KRAKEN_GATLING_XMX}"
        - name: KRAKEN_CONTAINER_TASKID
          value: "${KRAKEN_TASKID}"
        - name: KRAKEN_CONTAINER_TASKTYPE
          value: "${KRAKEN_TASKTYPE}"
        - name: KRAKEN_CONTAINER_HOSTID
          value: "${KRAKEN_HOSTID}"
        - name: KRAKEN_CONTAINER_NAME
          value: "${KRAKEN_APPLICATION_ID}-${KRAKEN_TASKID}-${KRAKEN_HOSTID}-${KRAKEN_GATLING_CONTAINER_NAME}"
        - name: KRAKEN_CONTAINER_LABEL
          value: "${KRAKEN_GATLING_CONTAINER_LABEL}"
        - name: KRAKEN_GATLING_JAVAOPTS
          value: "${KRAKEN_GATLING_JAVAOPTS} -Xmx${KRAKEN_GATLING_XMX}"
        - name: KRAKEN_STORAGE_URL
          value: "${KRAKEN_STORAGE_URL}"
        - name: KRAKEN_RUNTIME_URL
          value: "${KRAKEN_RUNTIME_URL}"
        - name: KRAKEN_GATLING_SIMULATION_CLASSNAME
          value: "${KRAKEN_GATLING_SIMULATION_CLASSNAME}"
        - name: KRAKEN_GATLING_SIMULATION_PACKAGENAME
          value: "${KRAKEN_GATLING_SIMULATION_PACKAGENAME}"
        - name: KRAKEN_GATLING_HARPATH_REMOTE
          value: "${KRAKEN_GATLING_HARPATH_REMOTE}"
        - name: KRAKEN_SECURITY_URL
          value: "${KRAKEN_SECURITY_URL}"
        - name: KRAKEN_SECURITY_WEBID
          value: "${KRAKEN_SECURITY_WEBID}"
        - name: KRAKEN_SECURITY_APIID
          value: "${KRAKEN_SECURITY_APIID}"
        - name: KRAKEN_SECURITY_APISECRET
          value: "${KRAKEN_SECURITY_APISECRET}"
        - name: KRAKEN_SECURITY_REALM
          value: "${KRAKEN_SECURITY_REALM}"
        - name: KRAKEN_SECURITY_ACCESSTOKEN
          value: "${KRAKEN_SECURITY_ACCESSTOKEN}"
        - name: KRAKEN_SECURITY_REFRESHTOKEN
          value: "${KRAKEN_SECURITY_REFRESHTOKEN}"
    -
      image: "octoperf/kraken-har-parser:${KRAKEN_VERSION}"
      name: "${KRAKEN_APPLICATION_ID}-${KRAKEN_TASKID}-${KRAKEN_HOSTID}-${KRAKEN_GATLING_SIDEKICK_NAME}"
      resources:
        limits:
          cpu: "${KRAKEN_SIDEKICK_CPU_LIMIT}"
          memory: "${KRAKEN_SIDEKICK_MEMORY_LIMIT}"
        requests:
          cpu: "${KRAKEN_SIDEKICK_CPU_REQUEST}"
          memory: "${KRAKEN_SIDEKICK_MEMORY_REQUEST}"
      env:
        - name: JAVA_OPTS
          value: "-Dspring.profiles.active=kubernetes -Xmx${KRAKEN_SIDEKICK_XMX}"
        - name: KRAKEN_CONTAINER_TASKID
          value: "${KRAKEN_TASKID}"
        - name: KRAKEN_CONTAINER_TASKTYPE
          value: "${KRAKEN_TASKTYPE}"
        - name: KRAKEN_CONTAINER_HOSTID
          value: "${KRAKEN_HOSTID}"
        - name: KRAKEN_CONTAINER_NAME
          value: "${KRAKEN_APPLICATION_ID}-${KRAKEN_TASKID}-${KRAKEN_HOSTID}-${KRAKEN_GATLING_SIDEKICK_NAME}"
        - name: KRAKEN_CONTAINER_LABEL
          value: "${KRAKEN_GATLING_SIDEKICK_LABEL}"
        - name: KRAKEN_STORAGE_URL
          value: "${KRAKEN_STORAGE_URL}"
        - name: KRAKEN_RUNTIME_URL
          value: "${KRAKEN_RUNTIME_URL}"
        - name: KRAKEN_ANALYSIS_URL
          value: "${KRAKEN_ANALYSIS_URL}"
        - name: KRAKEN_HARPARSER_REMOTE
          value: "${KRAKEN_GATLING_HARPATH_REMOTE}"
        - name: KRAKEN_SECURITY_URL
          value: "${KRAKEN_SECURITY_URL}"
        - name: KRAKEN_SECURITY_WEBID
          value: "${KRAKEN_SECURITY_WEBID}"
        - name: KRAKEN_SECURITY_APIID
          value: "${KRAKEN_SECURITY_APIID}"
        - name: KRAKEN_SECURITY_APISECRET
          value: "${KRAKEN_SECURITY_APISECRET}"
        - name: KRAKEN_SECURITY_REALM
          value: "${KRAKEN_SECURITY_REALM}"
        - name: KRAKEN_SECURITY_ACCESSTOKEN
          value: "${KRAKEN_SECURITY_ACCESSTOKEN}"
        - name: KRAKEN_SECURITY_REFRESHTOKEN
          value: "${KRAKEN_SECURITY_REFRESHTOKEN}"
  nodeSelector:
    com.kraken/hostId: "${KRAKEN_HOSTID}"
  restartPolicy: Never
  terminationGracePeriodSeconds: 5